### ISSUE TITLE
Does this use a C or Fortran library?

### ISSUE THREAD

**Issue by mrkaspa** [Qqwy/tensor#1]

**Comment by Qqwy** [comment]
Hello! Thank you for your question!

Tensor is completely written in Elixir, and does _not_ wrap a library written in another language.

This does mean that if your matrix calculations need to _really_ be extremely efficient, you might want to use something else.

On the other hand, Tensor stores vectors/matrices/tensors in a _sparse_ way, which means that often, calculations are cheaper than when these same calculations would be performed on a matrix stored in a _terse_ way.

I will clarify this better in the Readme. Thank you!
