### ISSUE TITLE
Usage of Matrix.get or get_and_update?

### ISSUE THREAD

**Issue by wsmoak** [Qqwy/tensor#3]
I am trying to understand `Matrix.get/3` which is documented as 

https://hexdocs.pm/tensor/Matrix.html#get/3
```
get(matrix, index, default)
Returns the element at index from matrix. If index is out of bounds, returns default
```

What is the "index" of a matrix?  Does it mean the linear index as described in [this article](https://www.mathworks.com/company/newsletters/articles/matrix-indexing-in-matlab.html) meaning you stack the columns in one large array and index into that?

Based on the docs I expect "an element" to be the integer at some position, but instead I get back a Vector.

In my experiments, `Matrix.get` seems to be doing the same thing as `Matrix.row` except that I have to provide a default.

```
> mat = Matrix.new([[11,82,31],[14,25,96],[237,88,0]],3,3) 
#Matrix<(3×3)
┌                          ┐
│      11,      82,      31│
│      14,      25,      96│
│     237,      88,       0│
└                          ┘

> Matrix.get(mat,2,100)                                   
#Vector<(3)[237, 88, 0]>

> Matrix.get(mat,3,100)
100
```

vs.
```
> Matrix.row(mat,2)                                       
#Vector<(3)[237, 88, 0]>
```

I'm happy to add some tests or docs (or possibly attempt a fix) once I understand what it's supposed to do.  Thanks!

**Comment by wsmoak** [comment]
This is a precursor to how to use `get_and_update` because I initially tried something like this:
```
> Matrix.get_and_update(mat, 2, fn x -> x * x end)
** (ArithmeticError) bad argument in arithmetic expression
             :erlang.*(#Vector<(3)[237, 88, 0]>, #Vector<(3)[237, 88, 0]>)
    (tensor) lib/tensor.ex:224: Tensor.get_and_update/3
```

I don't see a way to update a single row/column position in the matrix.

I'm not having any luck updating the entire row either, and I don't see any tests for these methods that might hold a clue.  Thanks for any advice!

**Comment by Qqwy** [comment]
Unclear documentation is definitely something that needs to be fixed.

Indeed, `Matrix.get` is similar to `Matrix.row` but with an added default value (`Matrix.row` will return `nil` if the passed index is out of bounds).

`Matrix.get` and `Matrix.get_and_update` are part of the Access behavour. Usually you should not call them directly, but instead use the Kernel functions (`get_in`, `get_and_update_in`, `put_in`, `update_in`, etc.). 
The idea of these functions (the Kernel ones) is that you can pass them a list of keys to be invoked in turn on the structure:

```
iex> mat[1]                                               
#Vector<(3)[14, 25, 96]>
iex> get_in(mat, [1])
#Vector<(3)[14, 25, 96]>
iex> mat[1][0]
14
iex> get_in(mat, [1,0])
14
iex> put_in(mat, [1,0], 42)
#Matrix<(3×3)
┌                          ┐
│      11,      82,      31│
│      42,      25,      96│
│     237,      88,       0│
└                          ┘
>
iex> get_and_update_in(mat, [1,0], fn x -> {x, x * x} end) # like this, returns old value (14) while simultaneously storing 14*14 in the new matrix:
{14,
 #Matrix<(3×3)
┌                          ┐
│      11,      82,      31│
│     196,      25,      96│
│     237,      88,       0│
└                          ┘
>
}
```


I will improve the documentation to clarify:
1) how `Matrix.get` and `Matrix.get_and_update` work.
2) that they are part of the Access protocol and usually should only be used indirectly by calling those functions.
3) Add some examples and tests.


Thank you for this issue!

**Comment by wsmoak** [comment]
Thanks, that's what I needed!  I knew about accessing with `[][]` but not about `get_in`,  `put_in`, etc., in `Kernel`.
